#!/usr/bin/env zsh

driverName="JJOC"

for driverType in "MIC" "SPK"
do
    sudo rm -rf /Library/Audio/Plug-Ins/HAL/${driverName}${driverType}.driver
    sudo cp -R Installer/root/${driverName}${driverType}.driver /Library/Audio/Plug-Ins/HAL
    rm -rf Installer/root/${driverName}${driverType}.driver
done

sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
