#!/usr/bin/env zsh

sudo rm -rf /Library/Audio/Plug-Ins/HAL/JJOC2ch.driver
sudo cp -R Installer/root/JJOC2ch.driver /Library/Audio/Plug-Ins/HAL
sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
rm -rf Installer/root/JJOC2ch.driver

# sudo rm -rf /Library/Audio/Plug-Ins/HAL/JJOC16ch.driver
# sudo cp -R Installer/root/JJOC16ch.driver /Library/Audio/Plug-Ins/HAL
# sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
# rm -rf Installer/root/JJOC16ch.driver
